### ISSUE TITLE
Program not actually terminating after selecting cancel build

### ISSUE THREAD

**Issue by akuzmich** [mavidser/SublimeInput#12]
This is on Mac OSX using c++, the program continues running and I have to manually terminate it using activity monitor. Can be replicated I think by simply having a c++ program with an infinite loop in it. Is there something I am doing wrong that causes this behavior? By the way thanks for the excellent plugin :)

**Comment by akuzmich** [comment]
By the way a further note, it works great with Python, the program terminates properly and everything, so I guess it is a c++ specific problem. Also just to note I am using clang as my compiler for c++ if that makes a difference.

**Comment by mavidser** [comment]
Hi.
Thanks for pointing this out, and so sorry for taking this long to fix it.

I believe that the termination should be working fine now.

It should take a few hours for the update (3.0) to go live on [package control.](https://packagecontrol.io/packages/Sublime%20Input)

**Comment by akuzmich** [comment]
Hm thanks for looking into this :) I downloaded the 3.0 sublime-package however the same problem persists for me, I am not sure why. When I run a program with infinite while loop the process shows up in activity monitor as running, and hitting cancel build does not remove the process. Is there a different way of doing things that I should try? Thanks again!

**Comment by mavidser** [comment]
Can you try again with the new version? I hope it should be fixed now.

**Comment by akuzmich** [comment]
Hm now having put in the latest version the Build and Cancel Build menu selections and shortcuts don't seem to work, they are greyed out and un-selectable. Does that sound possible to you? Thanks for the help!

**Comment by mavidser** [comment]
Try reinstalling the plugin. Remove it from the packages/installed packages
directory and reinstall from the package control.

**Comment by akuzmich** [comment]
^ Ok will try but does installing from package control make a difference? I was just pasting it into the installed packages folder.

**Comment by akuzmich** [comment]
^ Yeah you were right, I install from package control and now Build and Cancel Build are selectable. But cancel build with infinite loop still does not work, now when I select Cancel Build nothing happens and process keeps running. Before it would show in the little window that build had been canceled but now it does not, so something has changed at least. However process still seems to keep running :(

**Comment by mavidser** [comment]
This is unexpected. Please run build and cancel on an infinite loop, and paste the logs (from view|show console) if any error shows up in there.

**Comment by mavidser** [comment]
I just pushed an update which I hope could fix the issue.
But if the issue still persists, and the logs give no error, then I'm at a loss for what the issue is.

Tell me if this works (3.1.1).
